### ISSUE TITLE
Tag a release

### ISSUE THREAD

**Issue by tedivm** [tylerwalts/puppet-jdk_oracle#36]
Running your module from the forge site results in a lot of errors that aren't in the master, as there have been a lot of bugfixes, particularly in relation to Ubuntu. 

Please tag a new release when you get a chance.

**Comment by tylerwalts** [comment]
Thanks for the reminder.  I'm merging some lint fixes in now to fix the Travis CI build, then will cut a fresh release to the forge.

**Comment by tylerwalts** [comment]
This was done, version 1.3.3 is in the forge.
