### ISSUE TITLE
Removal of params in suse.pp breaks jdk_oracle::suse

### ISSUE THREAD

**Issue by sharumpe** [tylerwalts/puppet-jdk_oracle#47]
It looks like the cleanup in 7ac8c4162c58d424885e5f5c848fa0d35c2c8726 got rid of the parameter declaration, which breaks jdk_oracle::suse, resulting in:
```
Invalid parameter version on Class[Jdk_oracle::Suse] at /etc/puppet/environments/production/modules/jdk_oracle/manifests/init.pp:251
```

**Comment by sharumpe** [comment]
OK, I missed that you'd removed the need for the parameter passing in suse.pp.  I'm committing a change to my fork to remove the parameters in the call to suse.pp in init.pp.  I'll do a pull request from there.

**Comment by tylerwalts** [comment]
Thanks for the PR!
