### ISSUE TITLE
Consider supporting the Oracle RPMs 

### ISSUE THREAD

**Issue by schrepfler** [tylerwalts/puppet-jdk_oracle#5]
Hi,
I've forked the module in order to bake in support for the RPM bundles which Oracle is shipping and seem to be more up-to-date than the current tgz bundle. As a side effect I've removed compatibility support for non-rpm OS'es and JDK6 as its not in my requirement scope and I was not quite sure how can I make both tgz and rpm work together without a more extensive puppet refactoring. Use code from here if interested
https://github.com/schrepfler/puppet-jdk_oracle

**Comment by tylerwalts** [comment]
It will involve some work to merge the two repos, plus in the year that has passed your module has gotten a thousand+ downloads from the forge, so I just updated the Readme to have a reference to your module.  I think this one would be easier to maintain if it just focuses on the tarball method.  I'm going to close this issue but would re-open if you feel strongly that these repos should be merged into one.

**Comment by schrepfler** [comment]
Thanks for the official endorsement, I need to polish it a bit more and update to the latest version but alas I'm very short on time these days (and been disconnected from the internet for two months at home).
