### ISSUE TITLE
Next release on Puppet forge?

### ISSUE THREAD

**Issue by 030** [tylerwalts/puppet-jdk_oracle#66]

**Comment by andreyev** [comment]
:+1:

**Comment by fvanboven** [comment]
We're currently working on a "commit" version, we would love to go to a "official" PuppetForge release again. 

Would love to see a new release!

**Comment by tylerwalts** [comment]
Sorry about the wait, and a new version 1.5.0 is now up on the forge from the latest in master.  I would like to get the tests working again, but at least it is on the forge now:

https://forge.puppet.com/tylerwalts/jdk_oracle/
