### ISSUE TITLE
Need an option to satisfy package manager dependencies 

### ISSUE THREAD

**Issue by hoshsadiq** [tylerwalts/puppet-jdk_oracle#71]
While Java is available etc when installed through, some packages (specifically installed through dpkg, and likely rpm too) may require have their dependency populated with `default-jre, default-jre-headless` amongst other java packages. This means that when installed, dpkg will resolve this as OpenJDK and therefore can result in both OpenJDK and Oracle JDK.

To solve this (at least for dpkg, I'm not sure about other package managers), we can add a new option (potentially set the default to true) which would do the following:
- Install the `equivs` packages (and any dependencies it requires, shouldn't many if there are)
- Use/generate a custom control file and run equivs on it.
There's plenty of control files created by others, we can take inspiration from them, or even just copy them (however note, when I had to do this at my old place, these seemed to be outdated a little). Examples:
  - https://github.com/nunogt/equivs-java
  - http://unix.stackexchange.com/questions/85928/how-to-make-apt-recognize-an-installed-tar-package
  - Perhaps the best place to take inspiration may be looking through the OpenJDK Debian package?
- Run equivs on the generated control file.
This should generate a Debian package.
- Run `dpkg -i {file.deb}` to install
- Clean up
  - Remove equivs if not installed prior to this operation
  - Remove generated Debian package and generated control file

**Comment by tylerwalts** [comment]
The value of using this module, and why I wrote the first version, is that it installs from the source tarball, so you can confidently use the same artifact across multiple environments & OS.  I was having pain at the time by the way different OS managed the packaged install and updates, and wanted to be very specific with it.

There are other modules that install using the OS's package manager system - the one that is supported by puppetlabs does this.

Have you tried the other Java modules for this use case, or am I not understanding the issue?
