### ISSUE TITLE
RHEL 7.3 - Never updates

### ISSUE THREAD

**Issue by markfaine** [tylerwalts/puppet-jdk_oracle#80]
I have JDK 1.8 update 111 installed already on the server and this module will not upgrade Java to update 131?  How can I make it always install the default Java 8 version?

**Comment by tylerwalts** [comment]
Until Oracle provides an API or legal way to scrape their pages to dynamically determine the latest stable release, I don't know that this is technically and/or legally possible.

See the convo on PR #79 with some related ideas on how to do this, but I'm going to close this one as working as designed (current design is to specify which one you want).
